services:
  vitepress:
    build: .
    # ports no longer needed as Caddy will handle external access
    volumes:
      - docs_build:/home/bun/app/.vitepress/dist
    command: >
      sh -ceux '
        bun install &&
        bun generate:thumbnails &&
        bun build:icons &&
        bun docs:build'

  caddy:
    image: caddy:2-alpine
    ports:
      - "8110:80"
      - "44310:443"
    volumes:
      - docs_build:/usr/share/caddy
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  docs_build:
  caddy_data:
  caddy_config:
